### ISSUE TITLE
Wifi & BL 相关屏蔽的针脚

### ISSUE THREAD

**Issue by ivothgle** [daggeryu/k650d-i5-d3-clover#3]
Google 一番后找到了 BCM95352hmb 的针脚说明

| Pin No. | Definition     | Basic Description                  | Type  |
| ------- | -------------- | ---------------------------------- | ----- |
| 20      | WLAN_DISABLE_L | WLAN disable control (Active low). | Input |
| 51      | BT_DISABLE_L   | BT disable control (Active low).   | Input |

出现蓝牙不可用，需要屏蔽 51 针脚
睡眠唤醒后 Wifi 打不开，需要屏蔽 20 针脚
如图
![tapein](https://user-images.githubusercontent.com/24858557/57173934-2ac9cb00-6e69-11e9-8e12-ab2efe55b3d7.jpg)

图片来源：[https://www.tenforums.com/network-sharing/115932-intel-ac-7260-wi-fi-pci-e-asus-g73sw-laptop-win10-pro-64-no-go-2.html#post1438095](https://www.tenforums.com/network-sharing/115932-intel-ac-7260-wi-fi-pci-e-asus-g73sw-laptop-win10-pro-64-no-go-2.html#post1438095)

**Comment by daggeryu** [comment]
感谢提供
