### ISSUE TITLE
i5 D2 不能用 USB 唤醒

### ISSUE THREAD

**Issue by ivothgle** [daggeryu/k650d-i5-d3-clover#4]
可能是 USB 端口不太一样，不能用 USB 唤醒，同时唤醒后显示 USB 未正常推出，想用 `Hackintool` 来修复，该怎么处理呢？

**Comment by daggeryu** [comment]
那你可能要提取你的dsdt重新改一下。因为这个电脑的usb定制我在dsdt里进行的，详细你可以搜索XHC看看，和你的usb对比一下。不能用usb唤醒是直接用我的sdt出现的吗，如果不是你可能打了0x0d补丁，那个会禁用usb唤醒。

**Comment by ivothgle** [comment]
嗯，没有用你的 DSDT 了，我用了 `USBPorts.kext` 来处理，独显我自己提取了 HotPatch 了

**Comment by daggeryu** [comment]
这款电脑用hotpatch屏蔽独显，再做了亮度调节，会出现开机风扇狂转，需要修改一下dsdt，你没有遇到吗。

**Comment by ivothgle** [comment]
我的没有这个问题，但是我修改的位置跟你不太一样 我参考的是这个做的http://bbs.pcbeta.com/viewthread-1686087-1-1.html ，有兴趣的话可以加个微信交流一下？

**Comment by daggeryu** [comment]
可以qq交流，我在不少群里，有问题可以咨询，我qq就是这个头像，我这款电脑已经卖了，如果你跟我同宽可以fork 一下我的，我可以帮助你继续更新这款电脑。

**Comment by ivothgle** [comment]
按头像找人有点不可能的，但是我已经发验证信息你了，通过一下 
另外我的 [EFI](https://github.com/ivothgle/Hackintosh) 也发布了
