### ISSUE TITLE
声卡无法驱动

### ISSUE THREAD

**Issue by omsfuk** [daggeryu/k650d-i5-d3-clover#6]
老哥，你是直接就用原版AppleALC+注入3就成功了？没改别的地方？比如定制？
我10.12.6各个id都试了，都没用。只好voodooHDA，关键是这玩意开机破音+麦克风超大背景音

**Comment by daggeryu** [comment]
这款电脑我从10.5开始玩的，12.6适用applealc没有问题啊。你试试换老版本的applealc+lilu试试看吧。目前合台电脑我已经卖了。

**Comment by omsfuk** [comment]
好的，谢老哥，已经解决了
